# Generated by Django 3.1.7 on 2021-03-25 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(max_length=1000, verbose_name='Контент')),
                ('likes', models.IntegerField(default=0, verbose_name='Лайки')),
                ('files', models.FileField(blank=True, null=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Сommentary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', max_length=100)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_manager.news')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Коммментарии',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Имя')),
                ('surname', models.CharField(max_length=75, null=True, verbose_name='Фамилия')),
                ('bio', models.TextField(default='', max_length=500, null=True, verbose_name='Описание')),
                ('avatar', models.ImageField(null=True, upload_to='', verbose_name='Фото')),
                ('status', models.CharField(default='', max_length=75, null=True, verbose_name='Статус')),
                ('birth_date', models.DateField(null=True, verbose_name='Дата рождения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профлиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'ordering': ['name', 'surname', 'birth_date'],
            },
        ),
    ]
