# Generated by Django 3.1.7 on 2021-03-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0003_auto_20210325_0126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профлиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AlterModelOptions(
            name='сommentary',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Коммментарии'},
        ),
        migrations.AddField(
            model_name='news',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Лайки'),
        ),
    ]
