# Generated by Django 3.1.7 on 2021-03-25 20:14

from django.db import migrations, models
import user_manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0006_auto_20210326_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=user_manager.models.news_files_directory),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to=user_manager.models.avatars_directory, verbose_name='Фото'),
        ),
    ]
