# Generated by Django 3.1.7 on 2021-03-27 17:33

from django.db import migrations, models
import django.db.models.deletion
import user_manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0008_auto_20210326_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='files',
        ),
        migrations.CreateModel(
            name='NewsFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=user_manager.models.news_files_directory)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='user_manager.news')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
