# Generated by Django 3.1.7 on 2021-04-04 13:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_manager', '0009_auto_20210327_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfile',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 4, 18, 31, 5, 564756), verbose_name='дата создания'),
        ),
        migrations.CreateModel(
            name='Repost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=datetime.datetime(2021, 4, 4, 18, 31, 5, 564756), verbose_name='дата создания')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repost', to='user_manager.news')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repost', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Репост',
                'verbose_name_plural': 'Репосты',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='user_manager.news')),
                ('repost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='user_manager.repost')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
