# Generated by Django 3.1.7 on 2021-04-04 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0010_auto_20210404_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsfile',
            name='create_date',
        ),
        migrations.AddField(
            model_name='news',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 4, 19, 6, 56, 372192), verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='repost',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 4, 19, 6, 56, 373191), verbose_name='дата создания'),
        ),
    ]
