# Generated by Django 3.1.7 on 2021-04-09 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0016_auto_20210407_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 23, 4, 30, 970920), verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='news',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 23, 4, 30, 969920), verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='repost',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 23, 4, 30, 969920), verbose_name='дата создания'),
        ),
    ]
