# Generated by Django 3.1.7 on 2021-04-10 18:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0017_auto_20210410_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='user_manager.posts'),
        ),
        migrations.AlterField(
            model_name='news',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 10, 23, 51, 14, 420225), verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='repost',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 10, 23, 51, 14, 421224), verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='repost',
            name='posts',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='repost', to='user_manager.posts'),
        ),
    ]
