# Generated by Django 3.1.7 on 2021-04-10 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0019_auto_20210411_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 11, 0, 35, 27, 626029), verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='news',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 11, 0, 35, 27, 623033), verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='repost',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 11, 0, 35, 27, 625052), verbose_name='дата создания'),
        ),
    ]
