# Generated by Django 3.1.7 on 2021-04-10 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0020_auto_20210411_0035'),
        ('user_manager', '0017_auto_20210409_2304'),
    ]

    operations = [
    ]
