# Generated by Django 3.1.7 on 2021-04-11 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0023_auto_20210411_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='news',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='repost',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='дата создания'),
        ),
    ]
