# Generated by Django 3.1.7 on 2021-04-15 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0021_auto_20210411_1902'),
        ('user_manager', '0024_auto_20210411_2311'),
    ]

    operations = [
    ]
