# Generated by Django 3.1.7 on 2021-04-15 17:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_manager', '0025_merge_20210415_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='news',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='repost',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='дата создания'),
        ),
        migrations.CreateModel(
            name='FriendShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='дата создания')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='Первый друг')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to=settings.AUTH_USER_MODEL, verbose_name='Второй друг')),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FriendRequests', to=settings.AUTH_USER_MODEL, verbose_name='кому отправлен запрос')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='our_requests', to=settings.AUTH_USER_MODEL, verbose_name='тот кто отправляет запрос')),
            ],
        ),
    ]
