# Generated by Django 3.1.7 on 2021-05-25 10:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_manager', '0030_auto_20210525_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='community_news',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='user_manager.communitypost'),
        )
    ]
